### ISSUE TITLE
1.18.2 error

### ISSUE THREAD

**Issue by Igilq** [ValkyrienSkies/Eureka#116]
When I wanted to launch valerien skies and erureka it was always crashiing with error code 1. When I removed those mods minecraft started normally

**Comment by ThePaste** [comment]
idk, maybe is your pc

**Comment by copperwarrior** [comment]
Please provide crash reports or logs for when this happened.

**Comment by Igilq** [comment]
Where should I upload crash log?

**Comment by copperwarrior** [comment]
Pastebin or github gist will work fine.

**Comment by Igilq** [comment]
Where I can find crash logs?

**Comment by Spiderach** [comment]
With the newer versions of Forge, the game usually crashes with "Error Code 1" when there is a mod missing that others are dependent on. It used to say specifically which mods were missing, but now we just get that non specific error code in the popup. 

Do you have Valkyrien Skies installed as well? Eureka needs that to work.

If that's not the issue you'll need to look at your latest log file. There usually isn't a crash report with error code one because it crashes too early into loading to make one. Since there's no crash report we have to hope that the regular console log mentions what the problem is. 

The log files are located in your install location (either .minecraft if you've installed things manually, or wherever your launcher is set up to put your Minecraft instances) under the folder named "logs". Open up "latest.log" after you've had a crash. Scroll up a little bit, and there might be an indented line where the console is telling you what mod is missing. something like:
[##:##:##] [main/ERROR]: Missing or unsupported mandatory dependencies:
___________Mod ID: '**missingmodname**', Requested by: '_installedmodname_', Expected range: '[###)', Actual version: '[MISSING]'
With the mod in **BOLD** being the one you need to get and the mod in _ITALICS_ being the one you currently have installed that's missing something it needs.

Hope this helps.

**Comment by Igilq** [comment]
i have latest.txt will it be ok or i should search for something else?

**Comment by hairmantherealhairman** [comment]
Hi there, I'm providing my personal crash log as I am also running into this [issue:[](url)](url)
[crash-2023-01-28_18.39.46-server.txt](https://github.com/ValkyrienSkies/Eureka/files/10528678/crash-2023-01-28_18.39.46-server.txt)

**Comment by Rubydesic** [comment]
> Hi there, I'm providing my personal crash log as I am also running into this [issue:](url) [crash-2023-01-28_18.39.46-server.txt](https://github.com/ValkyrienSkies/Eureka/files/10528678/crash-2023-01-28_18.39.46-server.txt)

You should make your own issue, and Valkyrien Skies is not compatible with OptiFine (and neither is the latest version of forge lmao)
