### ISSUE TITLE
Engine fuel items - add/remove

### ISSUE THREAD

**Issue by Ashendale** [ValkyrienSkies/Eureka#320]
I'm using Eureka with other mods and I have fuel items that I can make that are equivalent to coal.

Is there a place in the configs I can edit what counts as fuel? I've been looking and can't find it.

**Comment by millennIumAMbiguity** [comment]
Every Fuel value should work.
```java
// We check if something is fuel like this:
net.minecraft.world.level.block.entity.BaseContainerBlockEntity.AbstractFurnaceBlockEntity.isFuel(ItemStack)

// We get the fuel value like this:
net.minecraft.world.level.block.entity.FurnaceBlockEntity.getFuel()[ItemStack]
```

**Comment by Ashendale** [comment]
Unsure how I can check/edit those values but, for example, Ars Nouveau Fire Essence can smelt 20 items in a furnace and does not work on the engine

![image](https://github.com/ValkyrienSkies/Eureka/assets/14125391/8d875c05-23ab-4d70-85e8-c0b2b0f3f459)

**Comment by millennIumAMbiguity** [comment]
what version are you using?

**Comment by Ashendale** [comment]
1.3.0 beta 4

**Comment by eira132** [comment]
Seconded, biofuel pellets from [Create Crafts and Addons](https://modrinth.com/mod/createaddition) do not work, despite working in a vanilla furnace and the aircraft from [Immersive Aircraft](https://modrinth.com/mod/immersive-aircraft). Which is unfortunate, because biofuel pellets are an excellent fuel source otherwise.

Minecraft Version: 1.19.2
Eureka Version: 1.5.1 Beta 2
Forge Version: 43.3.5

**Comment by eira132** [comment]
Just looking into it on the surface, the implementation for Immersive Aircraft checks whether the item being placed into the fuel slot is burnable, instead of checking whether it is fuel:

```java
public boolean mayPlace(ItemStack stack) {
    return Utils.getFuelTime(stack) > 0;
}
```
[Link](https://github.com/Luke100000/ImmersiveAircraft/blob/dbc036b65e26795e167443ca8c224134818e84c7/common/src/main/java/immersive_aircraft/screen/slot/FuelSlot.java#L15)

```java
public static int getFuelTime(ItemStack fuel) {
    if (fuel.isEmpty()) {
        return 0;
    }

    // Custom fuel
    Map<String, Integer> fuelList = Config.getInstance().fuelList;
    String identifier = BuiltInRegistries.ITEM.getKey(fuel.getItem()).toString();
    if (fuelList.containsKey(identifier)) {
        return fuelList.get(identifier);
    }

    // Vanilla fuel
    if (Config.getInstance().acceptVanillaFuel) {
        int fuelTime = CobaltFuelRegistry.INSTANCE.get(fuel);
        if (fuelTime > 0) {
            return fuelTime;
        }
    }

    return 0;
}
```
[Link](https://github.com/Luke100000/ImmersiveAircraft/blob/dbc036b65e26795e167443ca8c224134818e84c7/common/src/main/java/immersive_aircraft/util/Utils.java#L53)
